# Generated by Django 2.0.3 on 2018-04-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dog_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=200, null=True)),
                ('height', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('life_span', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
