/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-06-11 13:25:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Feedbap</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("  height: 180px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("header h1 a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  letter-spacing: 10px;\r\n");
      out.write("  color: black;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("nav ul {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  padding: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("nav ul li {\r\n");
      out.write("  display: inline;\r\n");
      out.write("  padding: 0 10px;\r\n");
      out.write("  letter-spacing: 10px;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a:hover {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t<h1><a href=\"home.jsp\"><img src=\"image/feedbapLogo.png\" height=200px></a></h1></h1>\r\n");
      out.write("\t \r\n");
      out.write("\t</header>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t");
if (session.getAttribute("name")==null){
			
			System.out.println("11111");
      out.write("\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/list_user.jsp>HOME</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=login_logout/login.jsp>LOGIN</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=login_logout/registration.jsp>SIGN UP</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/customize.jsp>CUSTOMIZE</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/about.jsp>ABOUT</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/production.jsp>PRODUCTION</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/faq.jsp>FAQ</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/contact.jsp>CONTACT</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t");
} 
		else {
			System.out.println("222221");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li>");
      out.print(session.getAttribute("name").toString() + "님 안녕하세요!" );
      out.write("</li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/list_user.jsp>HOME</a></li>\r\n");
      out.write("\t\t\t<li><a href=login_logout/logout.jsp>LOGOUT</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=login_logout/mypage.jsp>MYPAGE</a></li>\r\n");
      out.write("\t\t\t<li><a href=login_logout/customize.jsp>CUSTOMIZE</a></li>\r\n");
      out.write("\t\t\t<li><a href=login_logout/about.jsp>ABOUT</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/production.jsp>PRODUCTION</a></li>\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/faq.jsp>FAQ</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li><a target=\"iframe1\" href=category/contact.jsp>CONTACT</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\r\n");
      out.write("      <iframe name=\"iframe1\" src=\"category/list_user.jsp\" seamless width=100% height=1000px scrolling=\"no\" frameborder=\"0\"> </iframe>\r\n");
      out.write("   \t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
