# Generated by Django 2.0.3 on 2018-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('serialNum', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('userID', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('userPW', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
