# Generated by Django 2.0.3 on 2018-05-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questDate', models.DateTimeField(auto_now=True)),
                ('questType', models.CharField(max_length=30)),
                ('questTypeFreq', models.IntegerField(null=True)),
                ('emailNeed', models.IntegerField(default=0, max_length=1)),
                ('serialNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbap.User')),
            ],
        ),
    ]
