# Generated by Django 2.0.3 on 2018-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbap', '0002_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm',
            name='emailNeed',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
