# Generated by Django 2.0.3 on 2018-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbap', '0003_auto_20180515_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breedName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('maxWeight', models.FloatField()),
                ('minWeight', models.FloatField()),
                ('lifespan', models.IntegerField()),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('videoNum', models.IntegerField(primary_key=True, serialize=False)),
                ('multiType', models.CharField(max_length=30)),
                ('videoType', models.CharField(max_length=30)),
                ('popular', models.IntegerField(default=0)),
                ('placeName', models.CharField(max_length=30)),
            ],
        ),
    ]
