# Generated by Django 2.0.3 on 2018-05-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbap', '0004_breed_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petId', models.IntegerField(primary_key=True, serialize=False)),
                ('petName', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=1)),
                ('weight', models.FloatField()),
                ('neutralization', models.CharField(default='F', max_length=1)),
                ('neutralizationDate', models.DateField(null=True)),
                ('obesityDegree', models.IntegerField()),
                ('activityDegree', models.IntegerField()),
                ('allergy', models.CharField(max_length=30, null=True)),
                ('taste', models.CharField(max_length=30, null=True)),
                ('healthIssue', models.CharField(max_length=30, null=True)),
                ('breedName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbap.Breed')),
                ('serialNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbap.User')),
            ],
        ),
    ]
