# Generated by Django 2.0.3 on 2018-05-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbap', '0005_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('nutrition', models.CharField(max_length=30)),
                ('calorie', models.FloatField()),
                ('ingredient', models.CharField(max_length=100)),
                ('mixportion', models.FloatField()),
                ('price', models.FloatField(default=0.0)),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbap.Pet')),
            ],
        ),
    ]
