# Generated by Django 2.0.3 on 2018-05-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbap', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('deliveryStatus', models.CharField(max_length=30)),
                ('expectedDeliveryDate', models.DateField(null=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbap.Order')),
            ],
        ),
    ]
